export interface Notification{
    id: number,
    type: string,
    description: string,
    creationDate: Date,
    srcImg: string,
    isTop10: boolean,
    newEpisodes: boolean,
}

export const notifications:Notification[] = [
    {
    id: 1,
    type: 'Estreno',
    description: 'Proyecto Géminis',
    creationDate: new Date(),
    srcImg: '/assets/notifications/Gemini_man.webp',
    isTop10: false,
    newEpisodes: false,
    },
    {
    id: 2,
    type: 'Estreno',
    description: 'Cangrejo Negro',
    creationDate: new Date(),
    srcImg: '/assets/notifications/Cangrejo-Negro.jpeg',
    isTop10: true,
    newEpisodes: true,
    },
    {
    id: 3,
    type: 'Estreno',
    description: 'Flash',
    creationDate: new Date(),
    srcImg: '/assets/notifications/The-Flash.webp',
    isTop10: false,
    newEpisodes: false,
    },
    {
    id: 4,
    type: 'Estreno',
    description: 'Proyecto Géminis',
    creationDate: new Date(),
    srcImg: '/assets/notifications/Gemini_man.webp',
    isTop10: false,
    newEpisodes: false,
    },
    {
    id: 5,
    type: 'Estreno',
    description: 'Cangrejo Negro',
    creationDate: new Date(),
    srcImg: '/assets/notifications/Cangrejo-Negro.jpeg',
    isTop10: true,
    newEpisodes: true,
    },
    {
    id: 6,
    type: 'Estreno',
    description: 'Flash',
    creationDate: new Date(),
    srcImg: '/assets/notifications/The-Flash.webp',
    isTop10: false,
    newEpisodes: false,
    },
    {
    id: 7,
    type: 'Estreno',
    description: 'Proyecto Géminis',
    creationDate: new Date(),
    srcImg: '/assets/notifications/Gemini_man.webp',
    isTop10: false,
    newEpisodes: false,
    },
    {
    id: 8,
    type: 'Estreno',
    description: 'Cangrejo Negro',
    creationDate: new Date(),
    srcImg: '/assets/notifications/Cangrejo-Negro.jpeg',
    isTop10: true,
    newEpisodes: true,
    },
    {
    id: 9,
    type: 'Estreno',
    description: 'Flash',
    creationDate: new Date(),
    srcImg: '/assets/notifications/The-Flash.webp',
    isTop10: false,
    newEpisodes: false,
    },

]
